[package]
name = "van-compiler-wasi"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
van-compiler = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
